### ISSUE TITLE
Version output always shows old version in "dry" mode.

### ISSUE THREAD

**Issue by timoknapp** [go-semantic-release/action#13]
Hi @christophwitzko ,

i just found another topic which afaik  feels like a bug. When I use the `dry`mode and afterwards print the outputs of the `version` I noticed, that it always reflects the old version and not the expected new version. The `changelog` output instead shows the new version. For better debugging purposes I would find it convenient to also show the new version as an output. Here are some logs:

```
Run go-semantic-release/action@v1
  with:
    github-token: ***
    changelog-file: CHANGELOG.md
    update-file: .version
    dry: true
downloading semantic-release@^2.5.0
running semantic-release...
/home/runner/work/_temp/b9924d6f-dfc7-4424-91cf-9bff3b1b7c4f --version-file --changelog CHANGELOG.md --token *** --dry --update .version
[go-semantic-release]: version: 2.9.0
[go-semantic-release]: ci-condition plugin: GitHub Actions@1.2.0
[go-semantic-release]: provider plugin: GitHub@1.4.0
[go-semantic-release]: getting default branch...
[go-semantic-release]: found default branch: master
[go-semantic-release]: found current branch: master
[go-semantic-release]: found current sha: d2cee028bb9c194de8d235da4f7d4bf4fc64a0e8
[go-semantic-release]: running CI condition...
[go-semantic-release]: getting latest release...
[go-semantic-release]: found version: 1.2.4+83
[go-semantic-release]: getting commits...
[go-semantic-release]: analyzing commits...
[go-semantic-release]: commit-analyzer plugin: default@1.3.0
[go-semantic-release]: calculating new version...
[go-semantic-release]: new version: 1.2.5
[go-semantic-release]: generating changelog...
[go-semantic-release]: changelog-generator plugin: default@1.3.1
[go-semantic-release]: DRY RUN: no release was created

echo "Version: 1.2.4"

echo "Changelog: ## 1.2.5 (2020-11-12)
  
  #### Chores
  
  * **merge:** master (d2cee028)
``` 

Regards
Timo

**Comment by christophwitzko** [comment]
Hey @timoknapp, the `update-file` config is for package manager files (like `package.json`).
On a dry run, no release is created, so the created version file is called `.version-unreleased`. Dry releases are not fully supported by `go-semantic-release/action`.

**Comment by timoknapp** [comment]
Okay I see. So if I need to retrieve the new version in a `dry` mode, I need to read the `.version-unreleased` file created by `go-semantic-release`?

**Comment by christophwitzko** [comment]
Yes, exactly!

**Comment by timoknapp** [comment]
One More thing. Is it possible to provide a template for the release notes? Such that it can look like the following:

# Changelog

### 🎁 Feature:

    ...

### 🔧 Fix:

    .....

**Comment by christophwitzko** [comment]
This would be a new feature in the [changelog-generator-default](https://github.com/go-semantic-release/changelog-generator-default).

**Comment by christophwitzko** [comment]
or an entirely new plugin

**Comment by timoknapp** [comment]
Okay, understood. Thanks

**Comment by christophwitzko** [comment]
I will close this issue for now, feel free to create a new one for the changelog templates here: https://github.com/go-semantic-release/changelog-generator-default/issues
