### ISSUE TITLE
please release to add force-bump-patch-version argument

### ISSUE THREAD

**Issue by Thierry-girod** [go-semantic-release/action#18]
Hi, 
Could you release the latest changes you've made with the argument force-bump-patch-version.

Best regards

**Comment by christophwitzko** [comment]
Thanks, I just triggered a new release. 🙏

**Comment by christophwitzko** [comment]
done: https://github.com/go-semantic-release/action/releases/tag/v1.12.0

**Comment by Thierry-girod** [comment]
Thanks
