### ISSUE TITLE
Changelog prepend configuration is not available

### ISSUE THREAD

**Issue by avillalain** [go-semantic-release/action#19]
Looking at the source code there is no option to add the prepend configuration parameter for the cli. Is there an alternative way to add it?

**Comment by christophwitzko** [comment]
Hi @avillalain, you are right, this parameter is not explicitly added to the GitHub action. I will do that next week and thanks for noticing. ☺️

**Comment by avillalain** [comment]
no worries,  I have a commit ready for it, let me finish the PR

**Comment by avillalain** [comment]
@christophwitzko PR is ready.

**Comment by christophwitzko** [comment]
@avillalain Thank you! 🙏
