### ISSUE TITLE
BREAKING CHANGES and versions below v1.0

### ISSUE THREAD

**Issue by rlinehan** [go-semantic-release/action#23]
I encountered an issue where we were on a pre-v1.0.0 version (via the `allow-initial-development-versions` option) and we added a commit with `BREAKING CHANGES:` in order to call it out in the release docs. However we didn't connect that this was going to release v1.0.0!

In order to instead release a new `v0.x.0` version we had to reset git history on the main branch to remove the `BREAKING CHANGES` from the commit message.

It would be nice if there were some guardrails in place to prevent accidentally releasing v1.0.0 before we're ready to when `allow-initial-development-versions` is set and we're still pre 1.0 release.

**Comment by christophwitzko** [comment]
Hi @rlinehan, thanks for reporting this bug! ☺️ I agree, when using this flag the version should stay below `1.0.0`.

**Comment by christophwitzko** [comment]
I fixed this in version [2.20.2](https://github.com/go-semantic-release/semantic-release/releases/tag/v2.20.2) 🙏 🎉

**Comment by rlinehan** [comment]
Thank you @christophwitzko! Really appreciate the quick fix! 💖
