### ISSUE TITLE
Can't use plugin from a branch other than the default branch?

### ISSUE THREAD

**Issue by cprice404** [go-semantic-release/action#25]
We are setting up a `release` branch on our project which we will periodically merge to from our default branch, when we are ready for releases to be shipped.

As far as I can tell, the only way to make this work for github is to specify `custom-arguments: '--no-ci'` (haven't fully tested yet) because of these two things:

https://github.com/go-semantic-release/semantic-release/blob/master/cmd/semantic-release/main.go#L173-L194
https://github.com/go-semantic-release/condition-github/blob/4c8af3fc516151423fff2f77eb08bf7082570676/pkg/condition/github.go#L42-L44

I don't really understand the logic behind enforcing that the release must be done from the default branch; it precludes some workflows that seem like they might be common/desirable.  A config option to specify the allowed branches would be a reasonable compromise, perhaps?

**Comment by christophwitzko** [comment]
Hi @cprice404, sorry for the late reply, and thanks for trying go-semantic-release! ☺️ 

The default configuration only allows releases from the default branch of the repository. This behavior can only be changed by using the `--no-ci` flag (as you already figured out) or by setting the `--maintained-version "*"` flag. The second option is a bit of a hack that tells semantic-release always to release, no matter which branch it is running on.

Your case of having a separate release branch might be more common than I thought, so I think it would make sense to allow configuring this behavior with a CLI flag.

**Comment by cprice404** [comment]
thank you!
