### ISSUE TITLE
403 Resource not accessible by integration

### ISSUE THREAD

**Issue by ngshiheng** [go-semantic-release/action#27]
Hi, I am encountering an issue whereby my workflow release job failed with the error message `403 Resource not accessible by integration []` when the action job tries to create a release.

I tried looking for similar open issues on this repo and also https://github.com/go-semantic-release/semantic-release but couldn't find any.

I have seen people recommend [adding permissions to the job](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs). However, I am not sure if this is the best way to do it.

Workflow release.yml

https://github.com/ngshiheng/michelin-my-maps/blob/37aa71de4285a7e1fe7e6002242c9f5d82905e1c/.github/workflows/release.yml

Error message:
```sh
POST https://api.github.com/repos/ngshiheng/michelin-my-maps/git/refs: 403 Resource not accessible by integration []
```

Job log:

https://github.com/ngshiheng/michelin-my-maps/actions/runs/3791048610/jobs/6679193276#step:3:26

**Comment by christophwitzko** [comment]
Hi @ngshiheng,

can you go to https://github.com/ngshiheng/michelin-my-maps/settings/actions and check if the "Workflow permissions" are set to "Read and write permissions":
<img width="770" alt="Screenshot 2023-01-14 at 13 10 20" src="https://user-images.githubusercontent.com/5558021/212471016-eeaf22dd-0e9d-4c47-b79c-9f88a97a28f3.png">

Otherwise, you can configure it directly in the workflow:
```yaml
permissions:
  contents: write
```
https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Comment by ngshiheng** [comment]
hey Chris, thanks for getting back to me so quickly. I can confirm that the Workflow permissions was already set to "Read and write permissions":

<img width="782" alt="Screenshot 2023-01-14 at 8 17 06 PM" src="https://user-images.githubusercontent.com/43508840/212471222-1aef6567-a875-4631-9fbc-5267c9c3f88e.png">

**Comment by christophwitzko** [comment]
Okay, can you try to add
```yaml
permissions:
  contents: write
```
to your [release.yml](https://github.com/ngshiheng/michelin-my-maps/blob/37aa71de4285a7e1fe7e6002242c9f5d82905e1c/.github/workflows/release.yml)

**Comment by ngshiheng** [comment]
ah, nice! that fixes it ([job](https://github.com/ngshiheng/michelin-my-maps/actions/runs/3918508271/jobs/6698966181) for reference). Thanks!

On a side note, I assume this is a recent change because this wasn't needed. I guess this should be added to the actions README docs now (or hopefully, there's a way around this internally https://github.com/go-semantic-release/semantic-release)

**Comment by christophwitzko** [comment]
Perfect! Yes, this seems very interesting, but I think it is a bug.

As you can see here at the failing job: https://github.com/ngshiheng/michelin-my-maps/actions/runs/3791048610/jobs/6698864126#step:1:19 all permissions are set to `write` (as it should be).

<img width="336" alt="Screenshot 2023-01-14 at 13 43 53" src="https://user-images.githubusercontent.com/5558021/212472117-a0c1aaeb-6fc4-487a-bd05-7b10d7e14a98.png">

**Comment by ngshiheng** [comment]
Here are some of the issues that I've found that seem relevant:

- https://github.com/actions/first-interaction/issues/10
- https://stackoverflow.com/questions/71500558/github-workflow-set-up-job-fails-with-the-error-resource-not-accessible-by-integ
- https://sjramblings.io/github-actions-resource-not-accessible-by-integration/

Seems like as of now, there's no other definitive workaround besides the one you recommended (which others have too). I'm not 100% sure if this is an actual bug or an intended side effect from the GitHub side (given they have docs around job `permissions` already).

**Comment by christophwitzko** [comment]
Thanks for sharing! I added a comment to the example in the README: https://github.com/go-semantic-release/action#usage
