### ISSUE TITLE
GHA issue

### ISSUE THREAD

**Issue by Tochemey** [go-semantic-release/action#31]
<img width="1381" alt="image" src="https://github.com/go-semantic-release/action/assets/1633645/dcb86c39-bdbc-4803-9413-9e3ac5039a19">

Is there a way around this?

**Comment by christophwitzko** [comment]
Hi @Tochemey, thanks for reporting this issue.
There was a hiccup today with the firestore database of the plugin registry. It seems to be fixed now, but will continue to monitor the situation.

If the plugin registry seems to be not working, you can configure semantic-release to use GitHub directly to download the plugins by setting `--plugin-resolver github` as custom argument.
